version: '3.3'

services:
  ui:
    image: todoui:v0.1
    ports:
      - '8090:8080'
  
  backend:
    image: todobackend:v0.1
    ports:
      - '8080:8080'

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: matthias
      POSTGRES_DB: mydb
   